#!/usr/bin/env bash
# This script is displaying the story of passwd

password=x
while IFS=: read -r username _ userid gid _ home shell
do
	echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $username"

done < /etc/passwd
