#!/usr/bin/env bash
# This script is displaying "Best School" 10 time

myvar=1

while [ $myvar -ne 11 ]
do
	if [ $myvar -eq 4 ]
	then
		echo "bad luck"
	elif [ $myvar -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi

	((myvar++))
done
