#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

hour=0
mins=1

while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	
	while [ $mins -le 59 ]
	do
		echo $mins
		((mins++))
	done
	
	mins=1
	((hour++))
done
